// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cmd.proto

package org.cn.monkey.cmd.proto;

public final class Command {
  private Command() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CmdOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 cmdType = 1;
    /**
     * <code>required int32 cmdType = 1;</code>
     */
    boolean hasCmdType();
    /**
     * <code>required int32 cmdType = 1;</code>
     */
    int getCmdType();

    // optional bytes content = 2;
    /**
     * <code>optional bytes content = 2;</code>
     */
    boolean hasContent();
    /**
     * <code>optional bytes content = 2;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code org.cn.monkey.cmd.proto.Cmd}
   */
  public static final class Cmd extends
      com.google.protobuf.GeneratedMessage
      implements CmdOrBuilder {
    // Use Cmd.newBuilder() to construct.
    private Cmd(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Cmd(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Cmd defaultInstance;
    public static Cmd getDefaultInstance() {
      return defaultInstance;
    }

    public Cmd getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Cmd(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cmdType_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_Cmd_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_Cmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cn.monkey.cmd.proto.Command.Cmd.class, org.cn.monkey.cmd.proto.Command.Cmd.Builder.class);
    }

    public static com.google.protobuf.Parser<Cmd> PARSER =
        new com.google.protobuf.AbstractParser<Cmd>() {
      public Cmd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cmd(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Cmd> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 cmdType = 1;
    public static final int CMDTYPE_FIELD_NUMBER = 1;
    private int cmdType_;
    /**
     * <code>required int32 cmdType = 1;</code>
     */
    public boolean hasCmdType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 cmdType = 1;</code>
     */
    public int getCmdType() {
      return cmdType_;
    }

    // optional bytes content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>optional bytes content = 2;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes content = 2;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private void initFields() {
      cmdType_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCmdType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cmdType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, content_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmdType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.cn.monkey.cmd.proto.Command.Cmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cn.monkey.cmd.proto.Command.Cmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Command.Cmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cn.monkey.cmd.proto.Command.Cmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Command.Cmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Command.Cmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Command.Cmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Command.Cmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Command.Cmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Command.Cmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.cn.monkey.cmd.proto.Command.Cmd prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.cn.monkey.cmd.proto.Cmd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.cn.monkey.cmd.proto.Command.CmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_Cmd_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_Cmd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cn.monkey.cmd.proto.Command.Cmd.class, org.cn.monkey.cmd.proto.Command.Cmd.Builder.class);
      }

      // Construct using org.cn.monkey.cmd.proto.Command.Cmd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmdType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_Cmd_descriptor;
      }

      public org.cn.monkey.cmd.proto.Command.Cmd getDefaultInstanceForType() {
        return org.cn.monkey.cmd.proto.Command.Cmd.getDefaultInstance();
      }

      public org.cn.monkey.cmd.proto.Command.Cmd build() {
        org.cn.monkey.cmd.proto.Command.Cmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cn.monkey.cmd.proto.Command.Cmd buildPartial() {
        org.cn.monkey.cmd.proto.Command.Cmd result = new org.cn.monkey.cmd.proto.Command.Cmd(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmdType_ = cmdType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cn.monkey.cmd.proto.Command.Cmd) {
          return mergeFrom((org.cn.monkey.cmd.proto.Command.Cmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cn.monkey.cmd.proto.Command.Cmd other) {
        if (other == org.cn.monkey.cmd.proto.Command.Cmd.getDefaultInstance()) return this;
        if (other.hasCmdType()) {
          setCmdType(other.getCmdType());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCmdType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cn.monkey.cmd.proto.Command.Cmd parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cn.monkey.cmd.proto.Command.Cmd) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 cmdType = 1;
      private int cmdType_ ;
      /**
       * <code>required int32 cmdType = 1;</code>
       */
      public boolean hasCmdType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 cmdType = 1;</code>
       */
      public int getCmdType() {
        return cmdType_;
      }
      /**
       * <code>required int32 cmdType = 1;</code>
       */
      public Builder setCmdType(int value) {
        bitField0_ |= 0x00000001;
        cmdType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cmdType = 1;</code>
       */
      public Builder clearCmdType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdType_ = 0;
        onChanged();
        return this;
      }

      // optional bytes content = 2;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content = 2;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes content = 2;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>optional bytes content = 2;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content = 2;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.cn.monkey.cmd.proto.Cmd)
    }

    static {
      defaultInstance = new Cmd(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.cn.monkey.cmd.proto.Cmd)
  }

  public interface ResultMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 code = 1;
    /**
     * <code>required int32 code = 1;</code>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 1;</code>
     */
    int getCode();

    // optional string msg = 2;
    /**
     * <code>optional string msg = 2;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code org.cn.monkey.cmd.proto.ResultMessage}
   */
  public static final class ResultMessage extends
      com.google.protobuf.GeneratedMessage
      implements ResultMessageOrBuilder {
    // Use ResultMessage.newBuilder() to construct.
    private ResultMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResultMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResultMessage defaultInstance;
    public static ResultMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ResultMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResultMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_ResultMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_ResultMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cn.monkey.cmd.proto.Command.ResultMessage.class, org.cn.monkey.cmd.proto.Command.ResultMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ResultMessage> PARSER =
        new com.google.protobuf.AbstractParser<ResultMessage>() {
      public ResultMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResultMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResultMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>required int32 code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    // optional string msg = 2;
    public static final int MSG_FIELD_NUMBER = 2;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 2;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      code_ = 0;
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.cn.monkey.cmd.proto.Command.ResultMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cn.monkey.cmd.proto.Command.ResultMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Command.ResultMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cn.monkey.cmd.proto.Command.ResultMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Command.ResultMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Command.ResultMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Command.ResultMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Command.ResultMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Command.ResultMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Command.ResultMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.cn.monkey.cmd.proto.Command.ResultMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.cn.monkey.cmd.proto.ResultMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.cn.monkey.cmd.proto.Command.ResultMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_ResultMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_ResultMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cn.monkey.cmd.proto.Command.ResultMessage.class, org.cn.monkey.cmd.proto.Command.ResultMessage.Builder.class);
      }

      // Construct using org.cn.monkey.cmd.proto.Command.ResultMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_ResultMessage_descriptor;
      }

      public org.cn.monkey.cmd.proto.Command.ResultMessage getDefaultInstanceForType() {
        return org.cn.monkey.cmd.proto.Command.ResultMessage.getDefaultInstance();
      }

      public org.cn.monkey.cmd.proto.Command.ResultMessage build() {
        org.cn.monkey.cmd.proto.Command.ResultMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cn.monkey.cmd.proto.Command.ResultMessage buildPartial() {
        org.cn.monkey.cmd.proto.Command.ResultMessage result = new org.cn.monkey.cmd.proto.Command.ResultMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cn.monkey.cmd.proto.Command.ResultMessage) {
          return mergeFrom((org.cn.monkey.cmd.proto.Command.ResultMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cn.monkey.cmd.proto.Command.ResultMessage other) {
        if (other == org.cn.monkey.cmd.proto.Command.ResultMessage.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000002;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cn.monkey.cmd.proto.Command.ResultMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cn.monkey.cmd.proto.Command.ResultMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 code = 1;
      private int code_ ;
      /**
       * <code>required int32 code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      // optional string msg = 2;
      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 2;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.cn.monkey.cmd.proto.ResultMessage)
    }

    static {
      defaultInstance = new ResultMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.cn.monkey.cmd.proto.ResultMessage)
  }

  public interface PackageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;
    /**
     * <code>optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;</code>
     */
    boolean hasResultMsg();
    /**
     * <code>optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;</code>
     */
    org.cn.monkey.cmd.proto.Command.ResultMessage getResultMsg();
    /**
     * <code>optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;</code>
     */
    org.cn.monkey.cmd.proto.Command.ResultMessageOrBuilder getResultMsgOrBuilder();

    // optional int32 cmdType = 2;
    /**
     * <code>optional int32 cmdType = 2;</code>
     */
    boolean hasCmdType();
    /**
     * <code>optional int32 cmdType = 2;</code>
     */
    int getCmdType();

    // optional bytes content = 3;
    /**
     * <code>optional bytes content = 3;</code>
     */
    boolean hasContent();
    /**
     * <code>optional bytes content = 3;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code org.cn.monkey.cmd.proto.Package}
   */
  public static final class Package extends
      com.google.protobuf.GeneratedMessage
      implements PackageOrBuilder {
    // Use Package.newBuilder() to construct.
    private Package(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Package(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Package defaultInstance;
    public static Package getDefaultInstance() {
      return defaultInstance;
    }

    public Package getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Package(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.cn.monkey.cmd.proto.Command.ResultMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = resultMsg_.toBuilder();
              }
              resultMsg_ = input.readMessage(org.cn.monkey.cmd.proto.Command.ResultMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(resultMsg_);
                resultMsg_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cmdType_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_Package_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_Package_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cn.monkey.cmd.proto.Command.Package.class, org.cn.monkey.cmd.proto.Command.Package.Builder.class);
    }

    public static com.google.protobuf.Parser<Package> PARSER =
        new com.google.protobuf.AbstractParser<Package>() {
      public Package parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Package(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Package> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;
    public static final int RESULTMSG_FIELD_NUMBER = 1;
    private org.cn.monkey.cmd.proto.Command.ResultMessage resultMsg_;
    /**
     * <code>optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;</code>
     */
    public boolean hasResultMsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;</code>
     */
    public org.cn.monkey.cmd.proto.Command.ResultMessage getResultMsg() {
      return resultMsg_;
    }
    /**
     * <code>optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;</code>
     */
    public org.cn.monkey.cmd.proto.Command.ResultMessageOrBuilder getResultMsgOrBuilder() {
      return resultMsg_;
    }

    // optional int32 cmdType = 2;
    public static final int CMDTYPE_FIELD_NUMBER = 2;
    private int cmdType_;
    /**
     * <code>optional int32 cmdType = 2;</code>
     */
    public boolean hasCmdType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 cmdType = 2;</code>
     */
    public int getCmdType() {
      return cmdType_;
    }

    // optional bytes content = 3;
    public static final int CONTENT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>optional bytes content = 3;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes content = 3;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private void initFields() {
      resultMsg_ = org.cn.monkey.cmd.proto.Command.ResultMessage.getDefaultInstance();
      cmdType_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasResultMsg()) {
        if (!getResultMsg().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, resultMsg_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cmdType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, content_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, resultMsg_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cmdType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.cn.monkey.cmd.proto.Command.Package parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cn.monkey.cmd.proto.Command.Package parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Command.Package parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cn.monkey.cmd.proto.Command.Package parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Command.Package parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Command.Package parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Command.Package parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Command.Package parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Command.Package parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Command.Package parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.cn.monkey.cmd.proto.Command.Package prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.cn.monkey.cmd.proto.Package}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.cn.monkey.cmd.proto.Command.PackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_Package_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_Package_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cn.monkey.cmd.proto.Command.Package.class, org.cn.monkey.cmd.proto.Command.Package.Builder.class);
      }

      // Construct using org.cn.monkey.cmd.proto.Command.Package.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResultMsgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (resultMsgBuilder_ == null) {
          resultMsg_ = org.cn.monkey.cmd.proto.Command.ResultMessage.getDefaultInstance();
        } else {
          resultMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_Package_descriptor;
      }

      public org.cn.monkey.cmd.proto.Command.Package getDefaultInstanceForType() {
        return org.cn.monkey.cmd.proto.Command.Package.getDefaultInstance();
      }

      public org.cn.monkey.cmd.proto.Command.Package build() {
        org.cn.monkey.cmd.proto.Command.Package result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cn.monkey.cmd.proto.Command.Package buildPartial() {
        org.cn.monkey.cmd.proto.Command.Package result = new org.cn.monkey.cmd.proto.Command.Package(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (resultMsgBuilder_ == null) {
          result.resultMsg_ = resultMsg_;
        } else {
          result.resultMsg_ = resultMsgBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cmdType_ = cmdType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cn.monkey.cmd.proto.Command.Package) {
          return mergeFrom((org.cn.monkey.cmd.proto.Command.Package)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cn.monkey.cmd.proto.Command.Package other) {
        if (other == org.cn.monkey.cmd.proto.Command.Package.getDefaultInstance()) return this;
        if (other.hasResultMsg()) {
          mergeResultMsg(other.getResultMsg());
        }
        if (other.hasCmdType()) {
          setCmdType(other.getCmdType());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasResultMsg()) {
          if (!getResultMsg().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cn.monkey.cmd.proto.Command.Package parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cn.monkey.cmd.proto.Command.Package) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;
      private org.cn.monkey.cmd.proto.Command.ResultMessage resultMsg_ = org.cn.monkey.cmd.proto.Command.ResultMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.cn.monkey.cmd.proto.Command.ResultMessage, org.cn.monkey.cmd.proto.Command.ResultMessage.Builder, org.cn.monkey.cmd.proto.Command.ResultMessageOrBuilder> resultMsgBuilder_;
      /**
       * <code>optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;</code>
       */
      public boolean hasResultMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;</code>
       */
      public org.cn.monkey.cmd.proto.Command.ResultMessage getResultMsg() {
        if (resultMsgBuilder_ == null) {
          return resultMsg_;
        } else {
          return resultMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;</code>
       */
      public Builder setResultMsg(org.cn.monkey.cmd.proto.Command.ResultMessage value) {
        if (resultMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resultMsg_ = value;
          onChanged();
        } else {
          resultMsgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;</code>
       */
      public Builder setResultMsg(
          org.cn.monkey.cmd.proto.Command.ResultMessage.Builder builderForValue) {
        if (resultMsgBuilder_ == null) {
          resultMsg_ = builderForValue.build();
          onChanged();
        } else {
          resultMsgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;</code>
       */
      public Builder mergeResultMsg(org.cn.monkey.cmd.proto.Command.ResultMessage value) {
        if (resultMsgBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              resultMsg_ != org.cn.monkey.cmd.proto.Command.ResultMessage.getDefaultInstance()) {
            resultMsg_ =
              org.cn.monkey.cmd.proto.Command.ResultMessage.newBuilder(resultMsg_).mergeFrom(value).buildPartial();
          } else {
            resultMsg_ = value;
          }
          onChanged();
        } else {
          resultMsgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;</code>
       */
      public Builder clearResultMsg() {
        if (resultMsgBuilder_ == null) {
          resultMsg_ = org.cn.monkey.cmd.proto.Command.ResultMessage.getDefaultInstance();
          onChanged();
        } else {
          resultMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;</code>
       */
      public org.cn.monkey.cmd.proto.Command.ResultMessage.Builder getResultMsgBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getResultMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;</code>
       */
      public org.cn.monkey.cmd.proto.Command.ResultMessageOrBuilder getResultMsgOrBuilder() {
        if (resultMsgBuilder_ != null) {
          return resultMsgBuilder_.getMessageOrBuilder();
        } else {
          return resultMsg_;
        }
      }
      /**
       * <code>optional .org.cn.monkey.cmd.proto.ResultMessage resultMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.cn.monkey.cmd.proto.Command.ResultMessage, org.cn.monkey.cmd.proto.Command.ResultMessage.Builder, org.cn.monkey.cmd.proto.Command.ResultMessageOrBuilder> 
          getResultMsgFieldBuilder() {
        if (resultMsgBuilder_ == null) {
          resultMsgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.cn.monkey.cmd.proto.Command.ResultMessage, org.cn.monkey.cmd.proto.Command.ResultMessage.Builder, org.cn.monkey.cmd.proto.Command.ResultMessageOrBuilder>(
                  resultMsg_,
                  getParentForChildren(),
                  isClean());
          resultMsg_ = null;
        }
        return resultMsgBuilder_;
      }

      // optional int32 cmdType = 2;
      private int cmdType_ ;
      /**
       * <code>optional int32 cmdType = 2;</code>
       */
      public boolean hasCmdType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 cmdType = 2;</code>
       */
      public int getCmdType() {
        return cmdType_;
      }
      /**
       * <code>optional int32 cmdType = 2;</code>
       */
      public Builder setCmdType(int value) {
        bitField0_ |= 0x00000002;
        cmdType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cmdType = 2;</code>
       */
      public Builder clearCmdType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cmdType_ = 0;
        onChanged();
        return this;
      }

      // optional bytes content = 3;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content = 3;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes content = 3;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>optional bytes content = 3;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content = 3;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.cn.monkey.cmd.proto.Package)
    }

    static {
      defaultInstance = new Package(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.cn.monkey.cmd.proto.Package)
  }

  public interface PackageGroupOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .org.cn.monkey.cmd.proto.Package packages = 1;
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
     */
    java.util.List<org.cn.monkey.cmd.proto.Command.Package> 
        getPackagesList();
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
     */
    org.cn.monkey.cmd.proto.Command.Package getPackages(int index);
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
     */
    int getPackagesCount();
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
     */
    java.util.List<? extends org.cn.monkey.cmd.proto.Command.PackageOrBuilder> 
        getPackagesOrBuilderList();
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
     */
    org.cn.monkey.cmd.proto.Command.PackageOrBuilder getPackagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.cn.monkey.cmd.proto.PackageGroup}
   */
  public static final class PackageGroup extends
      com.google.protobuf.GeneratedMessage
      implements PackageGroupOrBuilder {
    // Use PackageGroup.newBuilder() to construct.
    private PackageGroup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PackageGroup(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PackageGroup defaultInstance;
    public static PackageGroup getDefaultInstance() {
      return defaultInstance;
    }

    public PackageGroup getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PackageGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                packages_ = new java.util.ArrayList<org.cn.monkey.cmd.proto.Command.Package>();
                mutable_bitField0_ |= 0x00000001;
              }
              packages_.add(input.readMessage(org.cn.monkey.cmd.proto.Command.Package.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          packages_ = java.util.Collections.unmodifiableList(packages_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_PackageGroup_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_PackageGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cn.monkey.cmd.proto.Command.PackageGroup.class, org.cn.monkey.cmd.proto.Command.PackageGroup.Builder.class);
    }

    public static com.google.protobuf.Parser<PackageGroup> PARSER =
        new com.google.protobuf.AbstractParser<PackageGroup>() {
      public PackageGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PackageGroup(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PackageGroup> getParserForType() {
      return PARSER;
    }

    // repeated .org.cn.monkey.cmd.proto.Package packages = 1;
    public static final int PACKAGES_FIELD_NUMBER = 1;
    private java.util.List<org.cn.monkey.cmd.proto.Command.Package> packages_;
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
     */
    public java.util.List<org.cn.monkey.cmd.proto.Command.Package> getPackagesList() {
      return packages_;
    }
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
     */
    public java.util.List<? extends org.cn.monkey.cmd.proto.Command.PackageOrBuilder> 
        getPackagesOrBuilderList() {
      return packages_;
    }
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
     */
    public int getPackagesCount() {
      return packages_.size();
    }
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
     */
    public org.cn.monkey.cmd.proto.Command.Package getPackages(int index) {
      return packages_.get(index);
    }
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
     */
    public org.cn.monkey.cmd.proto.Command.PackageOrBuilder getPackagesOrBuilder(
        int index) {
      return packages_.get(index);
    }

    private void initFields() {
      packages_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPackagesCount(); i++) {
        if (!getPackages(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < packages_.size(); i++) {
        output.writeMessage(1, packages_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < packages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, packages_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.cn.monkey.cmd.proto.Command.PackageGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cn.monkey.cmd.proto.Command.PackageGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Command.PackageGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cn.monkey.cmd.proto.Command.PackageGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Command.PackageGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Command.PackageGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Command.PackageGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Command.PackageGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Command.PackageGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Command.PackageGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.cn.monkey.cmd.proto.Command.PackageGroup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.cn.monkey.cmd.proto.PackageGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.cn.monkey.cmd.proto.Command.PackageGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_PackageGroup_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_PackageGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cn.monkey.cmd.proto.Command.PackageGroup.class, org.cn.monkey.cmd.proto.Command.PackageGroup.Builder.class);
      }

      // Construct using org.cn.monkey.cmd.proto.Command.PackageGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPackagesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (packagesBuilder_ == null) {
          packages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          packagesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cn.monkey.cmd.proto.Command.internal_static_org_cn_monkey_cmd_proto_PackageGroup_descriptor;
      }

      public org.cn.monkey.cmd.proto.Command.PackageGroup getDefaultInstanceForType() {
        return org.cn.monkey.cmd.proto.Command.PackageGroup.getDefaultInstance();
      }

      public org.cn.monkey.cmd.proto.Command.PackageGroup build() {
        org.cn.monkey.cmd.proto.Command.PackageGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cn.monkey.cmd.proto.Command.PackageGroup buildPartial() {
        org.cn.monkey.cmd.proto.Command.PackageGroup result = new org.cn.monkey.cmd.proto.Command.PackageGroup(this);
        int from_bitField0_ = bitField0_;
        if (packagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            packages_ = java.util.Collections.unmodifiableList(packages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.packages_ = packages_;
        } else {
          result.packages_ = packagesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cn.monkey.cmd.proto.Command.PackageGroup) {
          return mergeFrom((org.cn.monkey.cmd.proto.Command.PackageGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cn.monkey.cmd.proto.Command.PackageGroup other) {
        if (other == org.cn.monkey.cmd.proto.Command.PackageGroup.getDefaultInstance()) return this;
        if (packagesBuilder_ == null) {
          if (!other.packages_.isEmpty()) {
            if (packages_.isEmpty()) {
              packages_ = other.packages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePackagesIsMutable();
              packages_.addAll(other.packages_);
            }
            onChanged();
          }
        } else {
          if (!other.packages_.isEmpty()) {
            if (packagesBuilder_.isEmpty()) {
              packagesBuilder_.dispose();
              packagesBuilder_ = null;
              packages_ = other.packages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              packagesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPackagesFieldBuilder() : null;
            } else {
              packagesBuilder_.addAllMessages(other.packages_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPackagesCount(); i++) {
          if (!getPackages(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cn.monkey.cmd.proto.Command.PackageGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cn.monkey.cmd.proto.Command.PackageGroup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .org.cn.monkey.cmd.proto.Package packages = 1;
      private java.util.List<org.cn.monkey.cmd.proto.Command.Package> packages_ =
        java.util.Collections.emptyList();
      private void ensurePackagesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          packages_ = new java.util.ArrayList<org.cn.monkey.cmd.proto.Command.Package>(packages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.cn.monkey.cmd.proto.Command.Package, org.cn.monkey.cmd.proto.Command.Package.Builder, org.cn.monkey.cmd.proto.Command.PackageOrBuilder> packagesBuilder_;

      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public java.util.List<org.cn.monkey.cmd.proto.Command.Package> getPackagesList() {
        if (packagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(packages_);
        } else {
          return packagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public int getPackagesCount() {
        if (packagesBuilder_ == null) {
          return packages_.size();
        } else {
          return packagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public org.cn.monkey.cmd.proto.Command.Package getPackages(int index) {
        if (packagesBuilder_ == null) {
          return packages_.get(index);
        } else {
          return packagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public Builder setPackages(
          int index, org.cn.monkey.cmd.proto.Command.Package value) {
        if (packagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePackagesIsMutable();
          packages_.set(index, value);
          onChanged();
        } else {
          packagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public Builder setPackages(
          int index, org.cn.monkey.cmd.proto.Command.Package.Builder builderForValue) {
        if (packagesBuilder_ == null) {
          ensurePackagesIsMutable();
          packages_.set(index, builderForValue.build());
          onChanged();
        } else {
          packagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public Builder addPackages(org.cn.monkey.cmd.proto.Command.Package value) {
        if (packagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePackagesIsMutable();
          packages_.add(value);
          onChanged();
        } else {
          packagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public Builder addPackages(
          int index, org.cn.monkey.cmd.proto.Command.Package value) {
        if (packagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePackagesIsMutable();
          packages_.add(index, value);
          onChanged();
        } else {
          packagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public Builder addPackages(
          org.cn.monkey.cmd.proto.Command.Package.Builder builderForValue) {
        if (packagesBuilder_ == null) {
          ensurePackagesIsMutable();
          packages_.add(builderForValue.build());
          onChanged();
        } else {
          packagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public Builder addPackages(
          int index, org.cn.monkey.cmd.proto.Command.Package.Builder builderForValue) {
        if (packagesBuilder_ == null) {
          ensurePackagesIsMutable();
          packages_.add(index, builderForValue.build());
          onChanged();
        } else {
          packagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public Builder addAllPackages(
          java.lang.Iterable<? extends org.cn.monkey.cmd.proto.Command.Package> values) {
        if (packagesBuilder_ == null) {
          ensurePackagesIsMutable();
          super.addAll(values, packages_);
          onChanged();
        } else {
          packagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public Builder clearPackages() {
        if (packagesBuilder_ == null) {
          packages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          packagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public Builder removePackages(int index) {
        if (packagesBuilder_ == null) {
          ensurePackagesIsMutable();
          packages_.remove(index);
          onChanged();
        } else {
          packagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public org.cn.monkey.cmd.proto.Command.Package.Builder getPackagesBuilder(
          int index) {
        return getPackagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public org.cn.monkey.cmd.proto.Command.PackageOrBuilder getPackagesOrBuilder(
          int index) {
        if (packagesBuilder_ == null) {
          return packages_.get(index);  } else {
          return packagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public java.util.List<? extends org.cn.monkey.cmd.proto.Command.PackageOrBuilder> 
           getPackagesOrBuilderList() {
        if (packagesBuilder_ != null) {
          return packagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(packages_);
        }
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public org.cn.monkey.cmd.proto.Command.Package.Builder addPackagesBuilder() {
        return getPackagesFieldBuilder().addBuilder(
            org.cn.monkey.cmd.proto.Command.Package.getDefaultInstance());
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public org.cn.monkey.cmd.proto.Command.Package.Builder addPackagesBuilder(
          int index) {
        return getPackagesFieldBuilder().addBuilder(
            index, org.cn.monkey.cmd.proto.Command.Package.getDefaultInstance());
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Package packages = 1;</code>
       */
      public java.util.List<org.cn.monkey.cmd.proto.Command.Package.Builder> 
           getPackagesBuilderList() {
        return getPackagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.cn.monkey.cmd.proto.Command.Package, org.cn.monkey.cmd.proto.Command.Package.Builder, org.cn.monkey.cmd.proto.Command.PackageOrBuilder> 
          getPackagesFieldBuilder() {
        if (packagesBuilder_ == null) {
          packagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.cn.monkey.cmd.proto.Command.Package, org.cn.monkey.cmd.proto.Command.Package.Builder, org.cn.monkey.cmd.proto.Command.PackageOrBuilder>(
                  packages_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          packages_ = null;
        }
        return packagesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.cn.monkey.cmd.proto.PackageGroup)
    }

    static {
      defaultInstance = new PackageGroup(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.cn.monkey.cmd.proto.PackageGroup)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_cn_monkey_cmd_proto_Cmd_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_cn_monkey_cmd_proto_Cmd_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_cn_monkey_cmd_proto_ResultMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_cn_monkey_cmd_proto_ResultMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_cn_monkey_cmd_proto_Package_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_cn_monkey_cmd_proto_Package_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_cn_monkey_cmd_proto_PackageGroup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_cn_monkey_cmd_proto_PackageGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tCmd.proto\022\027org.cn.monkey.cmd.proto\"\'\n\003" +
      "Cmd\022\017\n\007cmdType\030\001 \002(\005\022\017\n\007content\030\002 \001(\014\"*\n" +
      "\rResultMessage\022\014\n\004code\030\001 \002(\005\022\013\n\003msg\030\002 \001(" +
      "\t\"f\n\007Package\0229\n\tresultMsg\030\001 \001(\0132&.org.cn" +
      ".monkey.cmd.proto.ResultMessage\022\017\n\007cmdTy" +
      "pe\030\002 \001(\005\022\017\n\007content\030\003 \001(\014\"B\n\014PackageGrou" +
      "p\0222\n\010packages\030\001 \003(\0132 .org.cn.monkey.cmd." +
      "proto.PackageB\013B\007CommandH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_cn_monkey_cmd_proto_Cmd_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_cn_monkey_cmd_proto_Cmd_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_cn_monkey_cmd_proto_Cmd_descriptor,
              new java.lang.String[] { "CmdType", "Content", });
          internal_static_org_cn_monkey_cmd_proto_ResultMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_cn_monkey_cmd_proto_ResultMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_cn_monkey_cmd_proto_ResultMessage_descriptor,
              new java.lang.String[] { "Code", "Msg", });
          internal_static_org_cn_monkey_cmd_proto_Package_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_cn_monkey_cmd_proto_Package_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_cn_monkey_cmd_proto_Package_descriptor,
              new java.lang.String[] { "ResultMsg", "CmdType", "Content", });
          internal_static_org_cn_monkey_cmd_proto_PackageGroup_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_org_cn_monkey_cmd_proto_PackageGroup_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_cn_monkey_cmd_proto_PackageGroup_descriptor,
              new java.lang.String[] { "Packages", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
