// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Entity.proto

package org.cn.monkey.cmd.proto;

public final class Entity {
  private Entity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CharacterOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string id = 1;
    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // optional string nickName = 2;
    /**
     * <code>optional string nickName = 2;</code>
     */
    boolean hasNickName();
    /**
     * <code>optional string nickName = 2;</code>
     */
    java.lang.String getNickName();
    /**
     * <code>optional string nickName = 2;</code>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    // optional string remoteAddress = 3;
    /**
     * <code>optional string remoteAddress = 3;</code>
     */
    boolean hasRemoteAddress();
    /**
     * <code>optional string remoteAddress = 3;</code>
     */
    java.lang.String getRemoteAddress();
    /**
     * <code>optional string remoteAddress = 3;</code>
     */
    com.google.protobuf.ByteString
        getRemoteAddressBytes();
  }
  /**
   * Protobuf type {@code org.cn.monkey.cmd.proto.Character}
   */
  public static final class Character extends
      com.google.protobuf.GeneratedMessage
      implements CharacterOrBuilder {
    // Use Character.newBuilder() to construct.
    private Character(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Character(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Character defaultInstance;
    public static Character getDefaultInstance() {
      return defaultInstance;
    }

    public Character getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Character(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              nickName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              remoteAddress_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cn.monkey.cmd.proto.Entity.internal_static_org_cn_monkey_cmd_proto_Character_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cn.monkey.cmd.proto.Entity.internal_static_org_cn_monkey_cmd_proto_Character_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cn.monkey.cmd.proto.Entity.Character.class, org.cn.monkey.cmd.proto.Entity.Character.Builder.class);
    }

    public static com.google.protobuf.Parser<Character> PARSER =
        new com.google.protobuf.AbstractParser<Character>() {
      public Character parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Character(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Character> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string nickName = 2;
    public static final int NICKNAME_FIELD_NUMBER = 2;
    private java.lang.Object nickName_;
    /**
     * <code>optional string nickName = 2;</code>
     */
    public boolean hasNickName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string nickName = 2;</code>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nickName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string remoteAddress = 3;
    public static final int REMOTEADDRESS_FIELD_NUMBER = 3;
    private java.lang.Object remoteAddress_;
    /**
     * <code>optional string remoteAddress = 3;</code>
     */
    public boolean hasRemoteAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string remoteAddress = 3;</code>
     */
    public java.lang.String getRemoteAddress() {
      java.lang.Object ref = remoteAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          remoteAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string remoteAddress = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRemoteAddressBytes() {
      java.lang.Object ref = remoteAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remoteAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
      nickName_ = "";
      remoteAddress_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRemoteAddressBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRemoteAddressBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.cn.monkey.cmd.proto.Entity.Character parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cn.monkey.cmd.proto.Entity.Character parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Entity.Character parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cn.monkey.cmd.proto.Entity.Character parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Entity.Character parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Entity.Character parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Entity.Character parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Entity.Character parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Entity.Character parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Entity.Character parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.cn.monkey.cmd.proto.Entity.Character prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.cn.monkey.cmd.proto.Character}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.cn.monkey.cmd.proto.Entity.CharacterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cn.monkey.cmd.proto.Entity.internal_static_org_cn_monkey_cmd_proto_Character_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cn.monkey.cmd.proto.Entity.internal_static_org_cn_monkey_cmd_proto_Character_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cn.monkey.cmd.proto.Entity.Character.class, org.cn.monkey.cmd.proto.Entity.Character.Builder.class);
      }

      // Construct using org.cn.monkey.cmd.proto.Entity.Character.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nickName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        remoteAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cn.monkey.cmd.proto.Entity.internal_static_org_cn_monkey_cmd_proto_Character_descriptor;
      }

      public org.cn.monkey.cmd.proto.Entity.Character getDefaultInstanceForType() {
        return org.cn.monkey.cmd.proto.Entity.Character.getDefaultInstance();
      }

      public org.cn.monkey.cmd.proto.Entity.Character build() {
        org.cn.monkey.cmd.proto.Entity.Character result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cn.monkey.cmd.proto.Entity.Character buildPartial() {
        org.cn.monkey.cmd.proto.Entity.Character result = new org.cn.monkey.cmd.proto.Entity.Character(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nickName_ = nickName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.remoteAddress_ = remoteAddress_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cn.monkey.cmd.proto.Entity.Character) {
          return mergeFrom((org.cn.monkey.cmd.proto.Entity.Character)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cn.monkey.cmd.proto.Entity.Character other) {
        if (other == org.cn.monkey.cmd.proto.Entity.Character.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasNickName()) {
          bitField0_ |= 0x00000002;
          nickName_ = other.nickName_;
          onChanged();
        }
        if (other.hasRemoteAddress()) {
          bitField0_ |= 0x00000004;
          remoteAddress_ = other.remoteAddress_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cn.monkey.cmd.proto.Entity.Character parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cn.monkey.cmd.proto.Entity.Character) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // optional string nickName = 2;
      private java.lang.Object nickName_ = "";
      /**
       * <code>optional string nickName = 2;</code>
       */
      public boolean hasNickName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string nickName = 2;</code>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nickName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nickName = 2;</code>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickName = 2;</code>
       */
      public Builder clearNickName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickName = 2;</code>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nickName_ = value;
        onChanged();
        return this;
      }

      // optional string remoteAddress = 3;
      private java.lang.Object remoteAddress_ = "";
      /**
       * <code>optional string remoteAddress = 3;</code>
       */
      public boolean hasRemoteAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string remoteAddress = 3;</code>
       */
      public java.lang.String getRemoteAddress() {
        java.lang.Object ref = remoteAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          remoteAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string remoteAddress = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRemoteAddressBytes() {
        java.lang.Object ref = remoteAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remoteAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string remoteAddress = 3;</code>
       */
      public Builder setRemoteAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        remoteAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string remoteAddress = 3;</code>
       */
      public Builder clearRemoteAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        remoteAddress_ = getDefaultInstance().getRemoteAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string remoteAddress = 3;</code>
       */
      public Builder setRemoteAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        remoteAddress_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.cn.monkey.cmd.proto.Character)
    }

    static {
      defaultInstance = new Character(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.cn.monkey.cmd.proto.Character)
  }

  public interface RoomDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 id = 1;
    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    // optional bool isClosed = 2;
    /**
     * <code>optional bool isClosed = 2;</code>
     */
    boolean hasIsClosed();
    /**
     * <code>optional bool isClosed = 2;</code>
     */
    boolean getIsClosed();

    // optional bool hasAudio = 3;
    /**
     * <code>optional bool hasAudio = 3;</code>
     */
    boolean hasHasAudio();
    /**
     * <code>optional bool hasAudio = 3;</code>
     */
    boolean getHasAudio();

    // optional bool hasVideo = 4;
    /**
     * <code>optional bool hasVideo = 4;</code>
     */
    boolean hasHasVideo();
    /**
     * <code>optional bool hasVideo = 4;</code>
     */
    boolean getHasVideo();

    // optional string master = 5;
    /**
     * <code>optional string master = 5;</code>
     */
    boolean hasMaster();
    /**
     * <code>optional string master = 5;</code>
     */
    java.lang.String getMaster();
    /**
     * <code>optional string master = 5;</code>
     */
    com.google.protobuf.ByteString
        getMasterBytes();

    // repeated .org.cn.monkey.cmd.proto.Character characters = 6;
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
     */
    java.util.List<org.cn.monkey.cmd.proto.Entity.Character> 
        getCharactersList();
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
     */
    org.cn.monkey.cmd.proto.Entity.Character getCharacters(int index);
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
     */
    int getCharactersCount();
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
     */
    java.util.List<? extends org.cn.monkey.cmd.proto.Entity.CharacterOrBuilder> 
        getCharactersOrBuilderList();
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
     */
    org.cn.monkey.cmd.proto.Entity.CharacterOrBuilder getCharactersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.cn.monkey.cmd.proto.RoomData}
   */
  public static final class RoomData extends
      com.google.protobuf.GeneratedMessage
      implements RoomDataOrBuilder {
    // Use RoomData.newBuilder() to construct.
    private RoomData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RoomData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RoomData defaultInstance;
    public static RoomData getDefaultInstance() {
      return defaultInstance;
    }

    public RoomData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RoomData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isClosed_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              hasAudio_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              hasVideo_ = input.readBool();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              master_ = input.readBytes();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                characters_ = new java.util.ArrayList<org.cn.monkey.cmd.proto.Entity.Character>();
                mutable_bitField0_ |= 0x00000020;
              }
              characters_.add(input.readMessage(org.cn.monkey.cmd.proto.Entity.Character.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          characters_ = java.util.Collections.unmodifiableList(characters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cn.monkey.cmd.proto.Entity.internal_static_org_cn_monkey_cmd_proto_RoomData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cn.monkey.cmd.proto.Entity.internal_static_org_cn_monkey_cmd_proto_RoomData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cn.monkey.cmd.proto.Entity.RoomData.class, org.cn.monkey.cmd.proto.Entity.RoomData.Builder.class);
    }

    public static com.google.protobuf.Parser<RoomData> PARSER =
        new com.google.protobuf.AbstractParser<RoomData>() {
      public RoomData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoomData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RoomData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional bool isClosed = 2;
    public static final int ISCLOSED_FIELD_NUMBER = 2;
    private boolean isClosed_;
    /**
     * <code>optional bool isClosed = 2;</code>
     */
    public boolean hasIsClosed() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool isClosed = 2;</code>
     */
    public boolean getIsClosed() {
      return isClosed_;
    }

    // optional bool hasAudio = 3;
    public static final int HASAUDIO_FIELD_NUMBER = 3;
    private boolean hasAudio_;
    /**
     * <code>optional bool hasAudio = 3;</code>
     */
    public boolean hasHasAudio() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool hasAudio = 3;</code>
     */
    public boolean getHasAudio() {
      return hasAudio_;
    }

    // optional bool hasVideo = 4;
    public static final int HASVIDEO_FIELD_NUMBER = 4;
    private boolean hasVideo_;
    /**
     * <code>optional bool hasVideo = 4;</code>
     */
    public boolean hasHasVideo() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool hasVideo = 4;</code>
     */
    public boolean getHasVideo() {
      return hasVideo_;
    }

    // optional string master = 5;
    public static final int MASTER_FIELD_NUMBER = 5;
    private java.lang.Object master_;
    /**
     * <code>optional string master = 5;</code>
     */
    public boolean hasMaster() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string master = 5;</code>
     */
    public java.lang.String getMaster() {
      java.lang.Object ref = master_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          master_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string master = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMasterBytes() {
      java.lang.Object ref = master_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        master_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .org.cn.monkey.cmd.proto.Character characters = 6;
    public static final int CHARACTERS_FIELD_NUMBER = 6;
    private java.util.List<org.cn.monkey.cmd.proto.Entity.Character> characters_;
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
     */
    public java.util.List<org.cn.monkey.cmd.proto.Entity.Character> getCharactersList() {
      return characters_;
    }
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
     */
    public java.util.List<? extends org.cn.monkey.cmd.proto.Entity.CharacterOrBuilder> 
        getCharactersOrBuilderList() {
      return characters_;
    }
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
     */
    public int getCharactersCount() {
      return characters_.size();
    }
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
     */
    public org.cn.monkey.cmd.proto.Entity.Character getCharacters(int index) {
      return characters_.get(index);
    }
    /**
     * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
     */
    public org.cn.monkey.cmd.proto.Entity.CharacterOrBuilder getCharactersOrBuilder(
        int index) {
      return characters_.get(index);
    }

    private void initFields() {
      id_ = 0;
      isClosed_ = false;
      hasAudio_ = false;
      hasVideo_ = false;
      master_ = "";
      characters_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isClosed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, hasAudio_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, hasVideo_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMasterBytes());
      }
      for (int i = 0; i < characters_.size(); i++) {
        output.writeMessage(6, characters_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isClosed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, hasAudio_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, hasVideo_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMasterBytes());
      }
      for (int i = 0; i < characters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, characters_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.cn.monkey.cmd.proto.Entity.RoomData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cn.monkey.cmd.proto.Entity.RoomData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Entity.RoomData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cn.monkey.cmd.proto.Entity.RoomData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Entity.RoomData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Entity.RoomData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Entity.RoomData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Entity.RoomData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.cn.monkey.cmd.proto.Entity.RoomData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cn.monkey.cmd.proto.Entity.RoomData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.cn.monkey.cmd.proto.Entity.RoomData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.cn.monkey.cmd.proto.RoomData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.cn.monkey.cmd.proto.Entity.RoomDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cn.monkey.cmd.proto.Entity.internal_static_org_cn_monkey_cmd_proto_RoomData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cn.monkey.cmd.proto.Entity.internal_static_org_cn_monkey_cmd_proto_RoomData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cn.monkey.cmd.proto.Entity.RoomData.class, org.cn.monkey.cmd.proto.Entity.RoomData.Builder.class);
      }

      // Construct using org.cn.monkey.cmd.proto.Entity.RoomData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCharactersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        isClosed_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        hasAudio_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        hasVideo_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        master_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        if (charactersBuilder_ == null) {
          characters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          charactersBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cn.monkey.cmd.proto.Entity.internal_static_org_cn_monkey_cmd_proto_RoomData_descriptor;
      }

      public org.cn.monkey.cmd.proto.Entity.RoomData getDefaultInstanceForType() {
        return org.cn.monkey.cmd.proto.Entity.RoomData.getDefaultInstance();
      }

      public org.cn.monkey.cmd.proto.Entity.RoomData build() {
        org.cn.monkey.cmd.proto.Entity.RoomData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cn.monkey.cmd.proto.Entity.RoomData buildPartial() {
        org.cn.monkey.cmd.proto.Entity.RoomData result = new org.cn.monkey.cmd.proto.Entity.RoomData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isClosed_ = isClosed_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hasAudio_ = hasAudio_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.hasVideo_ = hasVideo_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.master_ = master_;
        if (charactersBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            characters_ = java.util.Collections.unmodifiableList(characters_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.characters_ = characters_;
        } else {
          result.characters_ = charactersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cn.monkey.cmd.proto.Entity.RoomData) {
          return mergeFrom((org.cn.monkey.cmd.proto.Entity.RoomData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cn.monkey.cmd.proto.Entity.RoomData other) {
        if (other == org.cn.monkey.cmd.proto.Entity.RoomData.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasIsClosed()) {
          setIsClosed(other.getIsClosed());
        }
        if (other.hasHasAudio()) {
          setHasAudio(other.getHasAudio());
        }
        if (other.hasHasVideo()) {
          setHasVideo(other.getHasVideo());
        }
        if (other.hasMaster()) {
          bitField0_ |= 0x00000010;
          master_ = other.master_;
          onChanged();
        }
        if (charactersBuilder_ == null) {
          if (!other.characters_.isEmpty()) {
            if (characters_.isEmpty()) {
              characters_ = other.characters_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureCharactersIsMutable();
              characters_.addAll(other.characters_);
            }
            onChanged();
          }
        } else {
          if (!other.characters_.isEmpty()) {
            if (charactersBuilder_.isEmpty()) {
              charactersBuilder_.dispose();
              charactersBuilder_ = null;
              characters_ = other.characters_;
              bitField0_ = (bitField0_ & ~0x00000020);
              charactersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCharactersFieldBuilder() : null;
            } else {
              charactersBuilder_.addAllMessages(other.characters_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cn.monkey.cmd.proto.Entity.RoomData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cn.monkey.cmd.proto.Entity.RoomData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 id = 1;
      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional bool isClosed = 2;
      private boolean isClosed_ ;
      /**
       * <code>optional bool isClosed = 2;</code>
       */
      public boolean hasIsClosed() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool isClosed = 2;</code>
       */
      public boolean getIsClosed() {
        return isClosed_;
      }
      /**
       * <code>optional bool isClosed = 2;</code>
       */
      public Builder setIsClosed(boolean value) {
        bitField0_ |= 0x00000002;
        isClosed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isClosed = 2;</code>
       */
      public Builder clearIsClosed() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isClosed_ = false;
        onChanged();
        return this;
      }

      // optional bool hasAudio = 3;
      private boolean hasAudio_ ;
      /**
       * <code>optional bool hasAudio = 3;</code>
       */
      public boolean hasHasAudio() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool hasAudio = 3;</code>
       */
      public boolean getHasAudio() {
        return hasAudio_;
      }
      /**
       * <code>optional bool hasAudio = 3;</code>
       */
      public Builder setHasAudio(boolean value) {
        bitField0_ |= 0x00000004;
        hasAudio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool hasAudio = 3;</code>
       */
      public Builder clearHasAudio() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hasAudio_ = false;
        onChanged();
        return this;
      }

      // optional bool hasVideo = 4;
      private boolean hasVideo_ ;
      /**
       * <code>optional bool hasVideo = 4;</code>
       */
      public boolean hasHasVideo() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool hasVideo = 4;</code>
       */
      public boolean getHasVideo() {
        return hasVideo_;
      }
      /**
       * <code>optional bool hasVideo = 4;</code>
       */
      public Builder setHasVideo(boolean value) {
        bitField0_ |= 0x00000008;
        hasVideo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool hasVideo = 4;</code>
       */
      public Builder clearHasVideo() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hasVideo_ = false;
        onChanged();
        return this;
      }

      // optional string master = 5;
      private java.lang.Object master_ = "";
      /**
       * <code>optional string master = 5;</code>
       */
      public boolean hasMaster() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string master = 5;</code>
       */
      public java.lang.String getMaster() {
        java.lang.Object ref = master_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          master_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string master = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMasterBytes() {
        java.lang.Object ref = master_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          master_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string master = 5;</code>
       */
      public Builder setMaster(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        master_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string master = 5;</code>
       */
      public Builder clearMaster() {
        bitField0_ = (bitField0_ & ~0x00000010);
        master_ = getDefaultInstance().getMaster();
        onChanged();
        return this;
      }
      /**
       * <code>optional string master = 5;</code>
       */
      public Builder setMasterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        master_ = value;
        onChanged();
        return this;
      }

      // repeated .org.cn.monkey.cmd.proto.Character characters = 6;
      private java.util.List<org.cn.monkey.cmd.proto.Entity.Character> characters_ =
        java.util.Collections.emptyList();
      private void ensureCharactersIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          characters_ = new java.util.ArrayList<org.cn.monkey.cmd.proto.Entity.Character>(characters_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.cn.monkey.cmd.proto.Entity.Character, org.cn.monkey.cmd.proto.Entity.Character.Builder, org.cn.monkey.cmd.proto.Entity.CharacterOrBuilder> charactersBuilder_;

      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public java.util.List<org.cn.monkey.cmd.proto.Entity.Character> getCharactersList() {
        if (charactersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(characters_);
        } else {
          return charactersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public int getCharactersCount() {
        if (charactersBuilder_ == null) {
          return characters_.size();
        } else {
          return charactersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public org.cn.monkey.cmd.proto.Entity.Character getCharacters(int index) {
        if (charactersBuilder_ == null) {
          return characters_.get(index);
        } else {
          return charactersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public Builder setCharacters(
          int index, org.cn.monkey.cmd.proto.Entity.Character value) {
        if (charactersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCharactersIsMutable();
          characters_.set(index, value);
          onChanged();
        } else {
          charactersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public Builder setCharacters(
          int index, org.cn.monkey.cmd.proto.Entity.Character.Builder builderForValue) {
        if (charactersBuilder_ == null) {
          ensureCharactersIsMutable();
          characters_.set(index, builderForValue.build());
          onChanged();
        } else {
          charactersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public Builder addCharacters(org.cn.monkey.cmd.proto.Entity.Character value) {
        if (charactersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCharactersIsMutable();
          characters_.add(value);
          onChanged();
        } else {
          charactersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public Builder addCharacters(
          int index, org.cn.monkey.cmd.proto.Entity.Character value) {
        if (charactersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCharactersIsMutable();
          characters_.add(index, value);
          onChanged();
        } else {
          charactersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public Builder addCharacters(
          org.cn.monkey.cmd.proto.Entity.Character.Builder builderForValue) {
        if (charactersBuilder_ == null) {
          ensureCharactersIsMutable();
          characters_.add(builderForValue.build());
          onChanged();
        } else {
          charactersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public Builder addCharacters(
          int index, org.cn.monkey.cmd.proto.Entity.Character.Builder builderForValue) {
        if (charactersBuilder_ == null) {
          ensureCharactersIsMutable();
          characters_.add(index, builderForValue.build());
          onChanged();
        } else {
          charactersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public Builder addAllCharacters(
          java.lang.Iterable<? extends org.cn.monkey.cmd.proto.Entity.Character> values) {
        if (charactersBuilder_ == null) {
          ensureCharactersIsMutable();
          super.addAll(values, characters_);
          onChanged();
        } else {
          charactersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public Builder clearCharacters() {
        if (charactersBuilder_ == null) {
          characters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          charactersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public Builder removeCharacters(int index) {
        if (charactersBuilder_ == null) {
          ensureCharactersIsMutable();
          characters_.remove(index);
          onChanged();
        } else {
          charactersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public org.cn.monkey.cmd.proto.Entity.Character.Builder getCharactersBuilder(
          int index) {
        return getCharactersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public org.cn.monkey.cmd.proto.Entity.CharacterOrBuilder getCharactersOrBuilder(
          int index) {
        if (charactersBuilder_ == null) {
          return characters_.get(index);  } else {
          return charactersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public java.util.List<? extends org.cn.monkey.cmd.proto.Entity.CharacterOrBuilder> 
           getCharactersOrBuilderList() {
        if (charactersBuilder_ != null) {
          return charactersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(characters_);
        }
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public org.cn.monkey.cmd.proto.Entity.Character.Builder addCharactersBuilder() {
        return getCharactersFieldBuilder().addBuilder(
            org.cn.monkey.cmd.proto.Entity.Character.getDefaultInstance());
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public org.cn.monkey.cmd.proto.Entity.Character.Builder addCharactersBuilder(
          int index) {
        return getCharactersFieldBuilder().addBuilder(
            index, org.cn.monkey.cmd.proto.Entity.Character.getDefaultInstance());
      }
      /**
       * <code>repeated .org.cn.monkey.cmd.proto.Character characters = 6;</code>
       */
      public java.util.List<org.cn.monkey.cmd.proto.Entity.Character.Builder> 
           getCharactersBuilderList() {
        return getCharactersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.cn.monkey.cmd.proto.Entity.Character, org.cn.monkey.cmd.proto.Entity.Character.Builder, org.cn.monkey.cmd.proto.Entity.CharacterOrBuilder> 
          getCharactersFieldBuilder() {
        if (charactersBuilder_ == null) {
          charactersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.cn.monkey.cmd.proto.Entity.Character, org.cn.monkey.cmd.proto.Entity.Character.Builder, org.cn.monkey.cmd.proto.Entity.CharacterOrBuilder>(
                  characters_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          characters_ = null;
        }
        return charactersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.cn.monkey.cmd.proto.RoomData)
    }

    static {
      defaultInstance = new RoomData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.cn.monkey.cmd.proto.RoomData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_cn_monkey_cmd_proto_Character_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_cn_monkey_cmd_proto_Character_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_cn_monkey_cmd_proto_RoomData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_cn_monkey_cmd_proto_RoomData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Entity.proto\022\027org.cn.monkey.cmd.proto\"" +
      "@\n\tCharacter\022\n\n\002id\030\001 \001(\t\022\020\n\010nickName\030\002 \001" +
      "(\t\022\025\n\rremoteAddress\030\003 \001(\t\"\224\001\n\010RoomData\022\n" +
      "\n\002id\030\001 \001(\005\022\020\n\010isClosed\030\002 \001(\010\022\020\n\010hasAudio" +
      "\030\003 \001(\010\022\020\n\010hasVideo\030\004 \001(\010\022\016\n\006master\030\005 \001(\t" +
      "\0226\n\ncharacters\030\006 \003(\0132\".org.cn.monkey.cmd" +
      ".proto.CharacterB\nB\006EntityH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_cn_monkey_cmd_proto_Character_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_cn_monkey_cmd_proto_Character_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_cn_monkey_cmd_proto_Character_descriptor,
              new java.lang.String[] { "Id", "NickName", "RemoteAddress", });
          internal_static_org_cn_monkey_cmd_proto_RoomData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_cn_monkey_cmd_proto_RoomData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_cn_monkey_cmd_proto_RoomData_descriptor,
              new java.lang.String[] { "Id", "IsClosed", "HasAudio", "HasVideo", "Master", "Characters", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
